#!/bin/bash
# Script to verify the authenticity of a YubiHSM device.
# 
# Steps:
# 1. Retrieve the device certificate stored in the YubiHSM.
# 2. Verify that the certificate is signed by YubiCo's CA.
# 3. Generate an ed25519 key with signing capability.
# 4. Generate an attestation certificate for the ed25519 key.
# 5. Verify the attestation certificate is signed by the device certificate.
# 6. Sign some data with the ed25519 key.
# 7. Verify the signature using the public key from the attestation certificate.

set -euo pipefail

yhsm_wrapper() {
    yubihsm-shell --connector yhusb:// -p password "$@"
}

trap 'echo "An error occurred. YubiHSM verification failed. Exiting."' ERR

# Retrieve the device certificate stored in the YubiHSM
cert=$(yhsm_wrapper -a get-opaque --outformat PEM)

# https://docs.yubico.com/hardware/yubihsm-2/hsm-2-user-guide/hsm2-core-concepts.html#pre-loaded-certificates
ca_cert=$(cat <<'EOF'
-----BEGIN CERTIFICATE-----
MIIFBzCCAu+gAwIBAgIEHM6S6zANBgkqhkiG9w0BAQsFADAhMR8wHQYDVQQDDBZZ
dWJpY28gWXViaUhTTSBSb290IENBMCAXDTE3MDEwMTAwMDAwMFoYDzIwNzExMDA1
MDAwMDAwWjAhMR8wHQYDVQQDDBZZdWJpY28gWXViaUhTTSBSb290IENBMIICIjAN
BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA4WqC8Krz1pXqgD4Bj3g/dosh/soy
dDCbNQ1uePeONXO5u4Kswi+jXPmcU9uqxIrNC6+t7Mwc+yyBAZBvIl6w+h5qwT7z
E7VTjeWBTP/4w0NXzgkPZgXWl6XIZNCJQfSSUxfh/NW7KCQySpDUGkR8hFHYwZTI
UD90/chv7lc1zcpaIgJDQ7m3IbPKKbaRrrc7ZUSB1cCFM7P6ESuJiTMKITNTMyW2
qoa8YTaAxHXIiiqmnff2ObtsPKtjfh8aHDdBdpZ8TqBCu8ht+3tpZpe2lnfqJBUG
N9wqIp+h1JLaKXN4NTr+VlUNEEGwMEJNKMtt3p1qxHmyHV4vSd5mOT4SY81MNL0C
v3HAHgR1lT7o8rMDTjB1PZP9v8Np2rpuvlog34eMsIBApP78zSjQrImQiHAYcADc
RZX6nSTOFyNdfjWtKxybdiFZpTpuLtGPwF7i3ISYQXambmaEqw83jCqIMMF4jFMk
KjA8UZnJRW+53pM5Gy6hQzhlJpwhE9d/L87VeR2ei0sidO1rDB9pQOdy9z41EBw4
pH5Aa99CPcOn16Eg4TS5838as2pG3xFgWBiVxipMW72pejBD5G5kk/hpbOW5QO6v
aXBLmngq4o3IySmM9J9IPRXuZrhmu2uafIvp3o67/lUcuqGEnxjG+Sj5q51g12E6
sVXauoxqhGOhllcCAwEAAaNFMEMwHQYDVR0OBBYEFFKoA9OFueJx/kakn9SHmy3/
yIycMBIGA1UdEwEB/wQIMAYBAf8CAQIwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3
DQEBCwUAA4ICAQBRyFzKyZYRnr8lWRHI8asrOMm7HMETWE4HziCYlrZkZNp2EVdy
ZFgzJqIwXI9hrYp1CWnow86rUhFjAdgGhhG/wEvyX97G0xPsNS3x77uF4RpNe7ry
44PcwXJWqo8JhdNCbSAVR+Tqm/k/WF7A+qflevS4K4G7ADlm0W41FBpehYMynC/G
3ykOtBTfLkOfeoJbTlhhwe7z3Oq9V7O+whTgUoeCKYW14d9xnmVM1uJvHcGl+fO3
9kgYfTsNwdJFVy/9Xq4b3QXpQSQ71JhL58JIpnkLqd5Utf4K1jAFu/bQQMWpdghw
S8D9kfnV/tpJ6lXtxMrjVtF0BO1EPvNv+nWeRog794KkID+KGIL+eF7lDpYe8rrV
aqB1wZJ9mPeqJBtD5T8E5FhuOzBBeM3sVh0d8OVh8P0QLhBVYAU23S99PRkb3hgx
gQ7gK8wdMaCekYG1Dw6i7TMVhDQd/ZRuo6vmyhtDrzVLc5eTwHpzba+OyDza/24s
kakyoyKReuLlpMby4WhuhTzptROImNmQpeSfEM6w2aJpsIO8BFVBkZSJCtHEfBgO
/QLNr17cvMmOIwFLAeHiWlgSWTrHOD/8O95d5iXrtXzOf2iPGA26JczJSeLjvnAA
tHEbofSLGYZdgbQ8mQpXzkBsuvX/wpDiDvB4mIfjDWQv9hgo0edbkRUhEA==
-----END CERTIFICATE-----
EOF
)

intermediate_cert=$(cat <<'EOF'
-----BEGIN CERTIFICATE-----
MIIELjCCAhagAwIBAgIDZuAUMA0GCSqGSIb3DQEBCwUAMCExHzAdBgNVBAMMFll1
YmljbyBZdWJpSFNNIFJvb3QgQ0EwIBcNMTcwMTAxMDAwMDAwWhgPMjA3MTEwMDUw
MDAwMDBaMCgxJjAkBgNVBAMMHVl1YmljbyBZdWJpSFNNIDY3NDIwMzYgU3ViLUNB
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3CHbP9E0idgDVwT9Kgu
nNPi3sFdcRAIKeQvLeGIP76AK/e80PYpRS/ZGw0s8qvpR669g0akz3xOVJj61q5c
Ol48OnEtIi/sukcZpUNOnNe4JKQlJmHFBXUtFg497T+YWqYY0ZEJeXhpzl0CZzEN
vQIoRn7dWI4+8iZ3LLUkZ0jQAR486HERw5+wcZi9jZd/16ZrWpEMu5WNpR2OzjPM
eoaPh6st7wvmEJSjUttPM1tagX2fgbz9hi86LMHeXUVFYij+yd1gLTVxJV+DQ1dU
1n+XpZoge84RBFVYCcK9qgyUjPJWQzKggu02Bg0UIAzL03dmYYHyii3XnuicNJI9
hwIDAQABo2YwZDAdBgNVHQ4EFgQU5F2l82GwkbMNjyxvoEDbb+9XkY4wHwYDVR0j
BBgwFoAUUqgD04W54nH+RqSf1IebLf/IjJwwEgYDVR0TAQH/BAgwBgEB/wIBATAO
BgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIBALX6NZ/qgB4zRxFFAEw0
ZDAX5BwcW1SN9q4mGWCeSMtPW5LT3ST20DPLKHrg1C+8a5ZX77EDYefEKT6TqbXG
KFgWCAzCdhSz4YJIaq8/XCTaM5O15l6byrV0UC4KboM4fLIve5fVRS3Nn3pf2lD3
7czTFjqnyZ+iM6i/OxpIJaULPO8yFG2nY2ZLdVDLB8AmF3E+W1nlyn9mpcXuSTRc
RSMtcQ6V5fV9UTnPriX2Lu2DkcK//xEhz4u6oisE94RNtIrtG3OJKMgCHDw4RzI0
Tl5yLLjqS9tHlIg39EfDZR0aglpBHA8NVjbbPFS2LWASpcdt029poAPLHOjtsmkf
Piqhni0RyndtjmrVS+l4tvXNRFwBRjJHHBNwNbIZrLvQG4jzOQmn//1OWOHl4q97
+MX6hy4c1Tri0rpRw4XmvusrO5lO6SQsvrSM8MqcwxDwPxhjipOMTNsYFYWBVRIr
H60yxz7w25coT6Rs3Pl6674JBUtv4tDCxSTiCG8KlvquovJJnUf3MIY5STtjXr1/
juA5/QnjReLuF/iOG6Gsy4U1Qn3q9BO8hlXWylb7RY96L7Iz3rto4pFmZCONousS
D1mJ+5XBTWEUZlp4as54oJhxF88/4kusPZ9ozMteMeax61BKyQBL7RaEl1KV7snX
ItgTwk7SgyLM0cZufUi0Rh/s
-----END CERTIFICATE-----
EOF
)

openssl x509 -in <(echo "$cert") -noout -text

fullchain="${intermediate_cert}"$'\n'"${ca_cert}"
openssl verify -CAfile <(echo "$fullchain") /dev/stdin <<< "$cert"
if [ $? -eq 0 ]; then
    # We have not validated yet whether the private key in YubiHSM matches the public key in the certificate.
    # So we still need to do that.
    echo "YubiHSM contains certificate signed by YubiCo CA."
else
    echo "YubiHSM authenticity verification failed."
    exit 1
fi

# Only generate the attestation-verification key if it does not already exist
attestation_verification_object=$(yhsm_wrapper -a list-objects -A any -l attestation-verification | grep attestation-verification || true)
if test -z "$attestation_verification_object"; then
    yhsm_wrapper -a generate-asymmetric-key -i 1 -l attestation-verification -A ed25519 -c sign-eddsa
fi

# Verifiy that the ed25519 attestation certificate is signed by the device certificate
attestation_certificate=$(yhsm_wrapper -a sign-attestation-certificate -i 1 --attestation-id 0 --outformat PEM)
openssl verify -CAfile <(echo "${cert}"$'\n'"${fullchain}") /dev/stdin <<< "$attestation_certificate" || {
    echo "Attestation certificate verification failed."
    exit 1
}
echo "Attestation certificate verified successfully."

# Extract public key from attestation certificate for usage in signature verification
attestation_pubkey=$(openssl x509 -in <(echo "$attestation_certificate") -pubkey -noout)

# Data to be signed for authenticity verification
sign_data=$(echo "Authenticity verification"; date +%s%N; echo -n "_")
echo "$attestation_pubkey" > /tmp/attestation_pubkey.pem
echo -n "$sign_data" > /tmp/sign_data.txt

# Sign the data with the ed25519 key in the YubiHSM
signed=$(yhsm_wrapper -a sign-eddsa -i 1 -A ed25519 --in /tmp/sign_data.txt --out /dev/stdout --outformat base64)
echo "$signed" | base64 -d > /tmp/signature.bin

# Verify the signature using the public key from the attestation certificate
openssl pkeyutl -verify -pubin -inkey /tmp/attestation_pubkey.pem -rawin -in /tmp/sign_data.txt -sigfile /tmp/signature.bin
echo "YubiHSM authenticity verification succeeded."
